### ISSUE TITLE
This blueprint you developed is very valuable to me

### ISSUE THREAD

**Issue by zeal607** [ecostanzi/generator-jhipster-modular-monolith#4]
This blueprint you developed is very valuable to me. I hope you can continue to adapt it to support JHipster 7.0.0
thank you~

By the way,
Do you have any idea or plan to implement a multi-level module? 
Is there an application scenario for this requirement? Is it reasonable and necessary？

**Comment by ecostanzi** [comment]
@zeal607 glad it helped. I'll work on Jhipster 7 support soon, but for now, I'm not planning to implement multi-level modules.

**Comment by ecostanzi** [comment]
BTW If you want to describe how a multi-level module would help you and describe the case a little bit more feel free to open another issue. For the migration to JH 7, I opened this https://github.com/ecostanzi/generator-jhipster-modular-monolith/issues/5.
